# Executive Summary - Single Source of Truth
# This file generates both Markdown and LaTeX versions of the executive summary
# Uses terminology variables for consistent language

section_id: "executive-summary"
title: "Executive Summary"

# Content sections with terminology variables
sections:
  purpose:
    title: "What BOOST Accomplishes"
    anchor: "boost-purpose"
    content: |
      The Biomass Open Origin Standard for Tracking (BOOST) solves the fundamental challenge of maintaining continuous, verifiable traceability through biomass supply chains—from standing trees to processed biofuels—without losing data integrity at critical transfer points where materials change hands, locations, or physical states.

      **Core Problem Addressed**: Traditional biomass tracking systems break down during material transfers, processing operations, and aggregation points, creating traceability gaps where data continuity is lost or becomes unreliable. This forces businesses to maintain separate, incompatible tracking systems for different regulatory requirements while increasing documentation burden and compliance costs.

      **BOOST's Solution**: A unified data standard built around **{{PRIMARY_UNIT}}** that maintain their identity throughout the supply chain using {{IDENTIFICATION_STRATEGY}}, technology-appropriate data capture, and comprehensive field structures that simultaneously satisfy multiple regulatory frameworks.

  design_principles:
    title: "Overarching Design Principles"
    anchor: "design-principles"
    content: |
      ### **{{PRIMARY_UNIT}} as Foundation**

      The {{PRIMARY_UNIT}} entity is the central organizing concept of the entire BOOST standard. Every other entity in the 33-entity data model either creates, modifies, measures, or references {{PRIMARY_UNIT}}s. This {{TRACEABILITY_MODEL}} reflects the physical reality of biomass operations:

      - **Harvest Level**: Individual logs, piles, or volume aggregations become initial TRUs with appropriate identification methods
      - **Transport Level**: TRUs move through critical tracking points (harvest\_site $\rightarrow$ skid\_road $\rightarrow$ forest\_road $\rightarrow$ mill\_entrance) while maintaining identity
      - **Processing Level**: Input TRUs are transformed into output TRUs with complete genealogical linkage
      - **Compliance Level**: TRU data aggregates automatically generate required documentation for multiple regulatory programs

      ### **Physical Reality Mapping**

      BOOST's structure directly mirrors real-world biomass supply chain operations:

      1. **Harvest Operations**: TRUs are created when biomass is harvested, with {{IDENTIFICATION_APPROACH}} capturing unique characteristics through technology-appropriate methods
      2. **Transportation Flow**: Critical tracking points represent actual physical locations where custody changes hands or materials are aggregated
      3. **Processing Stages**: Material transformations (whole logs $\rightarrow$ chips $\rightarrow$ pellets $\rightarrow$ biofuels) create new TRUs with documented input-output relationships
      4. **Multi-Species Reality**: Mixed-species piles and processing batches are represented through SpeciesComponent entities that maintain individual species data within composite TRUs

  tracking_framework:
    title: "{{TRACKING_FRAMEWORK_TITLE}}"
    anchor: "continuous-traceability"  
    content: |
      Unlike conventional systems that lose traceability when materials are transferred between different tracking systems, BOOST maintains {{DATA_LINKAGE}} through:

      - **Identity Persistence**: Progressive identification methods that maintain continuity through physical handling and transportation
      - **Relationship Preservation**: Parent-child TRU relationships that track material splits, merges, and transformations
      - **Automated Reconciliation**: Volume conservation validation and measurement reconciliation across all tracking points

  value_proposition:
    title: "Value Proposition: Why BOOST Reduces Costs and Complexity"
    anchor: "value-proposition"
    content: |
      ### **{{IDENTIFICATION_APPROACH_TITLE}} Benefits**

      BOOST's {{IDENTIFICATION_STRATEGY}} provides significant operational advantages over conventional single-method tracking approaches:

      **Traditional Approach Limitations**:
      - Manual tagging systems require physical labels that can be lost, damaged, or mislabeled
      - Operator data entry creates human error points and increases labor costs
      - Separate tracking for different species/grades multiplies documentation burden
      - System incompatibilities force duplicate data entry for different regulatory requirements

      **BOOST {{IDENTIFICATION_APPROACH_TITLE}} Advantages**:
      - **Technology-Appropriate Deployment**: Progressive identification methods from RFID tags to optical scanning based on operational readiness levels
      - **Method Redundancy**: Primary and secondary identification methods ensure continuity when individual methods fail
      - **Scalable Implementation**: Start with proven methods (RFID, QR codes) and evolve to advanced methods (optical scanning) as technology matures
      - **Cost-Effective Transition**: Incremental technology adoption minimizes upfront investment while maximizing long-term capability

      **Technology Readiness Approach**: BOOST supports identification methods across all Technology Readiness Levels (TRL 1-9), enabling immediate deployment with proven methods while maintaining upgrade paths to emerging technologies as they mature for production use.

      ### **Regulatory Compliance Through Strategic Field Combinations**

      BOOST's field structure enables rapid compliance documentation for multiple regulatory frameworks by strategically combining standard data elements:

      **California Low Carbon Fuel Standard (LCFS) Compliance**:
      - Pathway CI calculation: `LCFSPathway.pathwayCI` + `EnergyCarbon.benchmarkCI`
      - Volume reporting: `TraceableUnit.totalVolumeM3` + `MaterialProcessing.outputQuantity`
      - Feedstock verification: `SupplyBase.supplyBaseType` + `GeographicData` location validation

      **Renewable Fuel Standard (RFS) Compliance**:
      - Renewable identification: `Material.materialCategory` + `SpeciesComponent.species`
      - Volume tracking: `Transaction.quantityM3` aggregated across supply chain stages
      - Quality documentation: `TraceableUnit.qualityGrade` + `MoistureContent` measurements

      **EU RED-II Compliance**:
      - Sustainability certification: `CertificationScheme.schemeType` + `Certificate` validity
      - Land use verification: `GeographicData` + `SupplyBase.supplyBaseType`
      - Greenhouse gas calculations: `EnergyCarbon.ghgEmissions` + processing stage data

      **Multi-Framework Efficiency**: A single BOOST implementation captures all required data fields, eliminating the need for separate tracking systems and enabling automatic generation of compliance documentation for all major regulatory programs.

  tolerance_standards:
    title: "{{TOLERANCE_APPROACH_TITLE}} and Practical Considerations"
    anchor: "tolerance-standards"
    content: |
      BOOST recognizes that real-world biomass supply chains cannot achieve perfect volume/mass conservation or species composition accuracy:

      **Volume Tolerance Standards**:
      - **CARB Standard**: ±0.5% volume tolerance for LCFS reporting (as documented on specification page 57)
      - **Processing Tolerances**: Pelletizing operations may have higher acceptable variance due to moisture content changes and material densification
      - **De Minimis Thresholds**: Material losses during transport, handling, and processing below 1% can be treated as operational variance rather than tracking errors

      **Numeric Precision Guidelines**:
      - **Carbon Intensity Values**: 2 decimal places (e.g., benchmarkCI: 94.17) for regulatory reporting precision
      - **Volume Measurements**: 3 decimal places for cubic meter quantities to maintain accuracy across aggregation operations
      - **Composition Percentages**: 1 decimal place for species composition within multi-species TRUs

      **Field Inclusion Rationale**: BOOST includes sufficient data complexity to meet regulatory requirements while maintaining {{IMPLEMENTATION_STRATEGY}}. Fields are included based on:
      - Direct regulatory requirement across one or more major programs (LCFS, RFS, EU-RED)
      - Operational necessity for maintaining traceability integrity
      - Industry standard practice for biomass chain of custody documentation

      This strategic field selection ensures that BOOST implementations serve real-world business purposes by reducing compliance documentation burden while maintaining the data integrity required for sustainability verification and regulatory reporting across multiple jurisdictions.

# Variable mappings - these will be replaced with terminology values
variables:
  PRIMARY_UNIT: "TraceableUnits (TRUs)"
  IDENTIFICATION_STRATEGY: "progressive identification methods"
  TRACEABILITY_MODEL: "TRU-centric approach"
  DATA_LINKAGE: "continuous data linkage"
  TRACKING_FRAMEWORK_TITLE: "Continuous Traceability Framework"
  TOLERANCE_APPROACH_TITLE: "Tolerance Standards"
  IMPLEMENTATION_STRATEGY: "practical implementability"

# Output format specifications
output_formats:
  markdown:
    filename: "executive-summary.inc.md"
    header_prefix: "##"
    
  latex:
    filename: "executive-summary.tex"
    header_prefix: "\\subsection"
    section_commands:
      subsection: "\\subsubsection"
      anchor: "\\label"