# BOOST Documentation Terminology Configuration
# Single source of truth for all terminology used throughout the specification
# This ensures consistency across all generated documentation formats

# Core Framework Terms
tracking_approach:
  current: "continuous traceability framework" 
  deprecated: ["media-interruption-free tracking", "media-interruption-free traceability"]
  description: "The overall approach to maintaining traceability without data loss"

identification_strategy:
  current: "progressive identification framework"
  deprecated: ["media-interruption-free identification", "biometric-only identification"]
  description: "Multi-method identification approach accommodating technology readiness levels"

tracking_method:
  current: "continuous traceability"
  deprecated: ["media-interruption-free", "uninterrupted tracking"] 
  description: "Method of maintaining data continuity throughout supply chain"

# Technology Approach Terms
identification_approach:
  current: "multi-method identification"
  deprecated: ["biometric identification", "single-method identification"]
  description: "Using multiple identification methods with fallbacks"

implementation_strategy:
  current: "technology-appropriate deployment"
  deprecated: ["revolutionary deployment", "biometric-first deployment"]
  description: "Implementation approach based on technology readiness levels"

readiness_framework:
  current: "Technology Readiness Level (TRL) framework"
  deprecated: ["maturity-independent framework"]
  description: "Framework for assessing and implementing identification technologies"

# Entity and System Terms
primary_unit:
  current: "TraceableUnit (TRU)"
  deprecated: ["MaterialBatch"]
  description: "The fundamental unit of traceability in BOOST"

traceability_model:
  current: "TRU-centric model"
  deprecated: ["batch-centric model", "material-centric model"]
  description: "Data model organization around TraceableUnit entities"

identification_methods:
  current: ["RFID", "QR codes", "barcodes", "manual IDs", "photo documentation", "biometric", "hybrid"]
  deprecated: ["biometric-only", "tag-only"]
  description: "Available identification methods in deployment-ready priority order"

# Process Terms
data_linkage:
  current: "continuous data linkage"
  deprecated: ["unbroken data linkage", "media-interruption-free linkage"]
  description: "Maintaining data connections throughout processing"

validation_approach:
  current: "progressive validation"
  deprecated: ["perfect validation", "error-free validation"]
  description: "Validation approach accommodating real-world tolerances"

# Technology and Implementation Terms
technology_approach:
  current: "Technology Readiness Level (TRL) framework"
  deprecated: ["biometric-first approach", "revolutionary technology approach"]
  description: "Graduated technology adoption based on readiness levels"

deployment_strategy:
  current: "technology-appropriate deployment"
  deprecated: ["cutting-edge deployment", "biometric-only deployment"]
  description: "Deployment strategy matching technology readiness to operational needs"

identification_persistence:
  current: "identity persistence"
  deprecated: ["biometric persistence", "natural signature persistence"]
  description: "Maintaining identification across processing stages"

# Section Titles (for automatic replacement)
section_titles:
  traceability_section:
    current: "Continuous Traceability Framework"
    deprecated: ["Media-Interruption-Free Tracking", "Biometric Tracking"]
    
  identification_section:
    current: "Progressive Identification and Continuous Traceability"
    deprecated: ["Biometric Media-Interruption-Free Tracking", "Attachment-Free Tracking"]
    
  framework_section:
    current: "Multi-Method Identification Framework"
    deprecated: ["Biometric Identification Framework", "Media-Interruption-Free Framework"]
    
  tracking_framework_title:
    current: "Continuous Traceability Framework"
    deprecated: ["Media-Interruption-Free Tracking", "Biometric Persistence Framework"]

# Descriptive Terms
approach_descriptors:
  comprehensive: "comprehensive"  # vs "revolutionary"
  practical: "technology-appropriate"  # vs "cutting-edge"
  realistic: "implementation-ready"  # vs "breakthrough"
  flexible: "adaptable"  # vs "rigid"

# Compliance and Standards Terms
standards_approach:
  current: "regulatory compliance framework"
  deprecated: ["perfect compliance", "error-free compliance"]
  description: "Approach to meeting regulatory requirements with tolerance standards"

tolerance_approach:
  current: "practical tolerance standards"
  deprecated: ["zero-tolerance standards", "perfect accuracy requirements"]
  description: "Realistic tolerance standards for real-world implementation"

# Version and Status Terms
version_approach:
  current: "dynamic versioning"
  deprecated: ["hardcoded versioning"]
  description: "Git-tag-based version management"

development_status:
  current: "progressive implementation"
  deprecated: ["revolutionary change", "disruptive implementation"]
  description: "Phased implementation approach"

# Quality and Confidence Terms
confidence_framework:
  current: "confidence scoring system (0-100)"
  deprecated: ["binary confidence", "perfect/imperfect classification"]
  description: "Graduated confidence levels for identification methods"

validation_levels:
  high: "≥70% confidence"
  medium: "30-69% confidence"
  low: "<30% confidence (requires alternative method)"
  description: "Confidence thresholds for identification validation"

# Documentation Generation Terms
content_source:
  current: "schema-driven content generation"
  deprecated: ["manual content duplication"]
  description: "Single source of truth for all documentation content"

build_approach:
  current: "unified build system"
  deprecated: ["separate build processes"]
  description: "Single build process for all documentation formats"